In [5]:
# Example of Perceptron Work
import numpy as np
x = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([0,1,1,1])

In [6]:
x,y

(array([[0, 0],
        [0, 1],
        [1, 0],
        [1, 1]]),
 array([0, 1, 1, 1]))

In [7]:
w = np.array([1,1])
w

array([1, 1])

In [8]:
b = -0.5
b

-0.5

In [13]:
pred = []
for a in x:
    y_hat = np.dot(a,w)+b
    pred.append(activation(y_hat))

pred

[0, 1, 1, 1]

In [12]:
def activation(z):
    if z >= 0:
        return 1
    else:
        return 0

In [ ]:
#Sklearn Classification Algorithm
# 1 Logistic Regression
# 2 K Nearest Neighbors Algorithm (KNN)
# 3 Decision Tree Algorithm 
# 4 Random Forest Algorithm 
# 5 Support Vector Machine Algorithm (SVM)
# 6 Naive Bayes Algorithm 